### ISSUE TITLE
hello  大佬，文章【前端性能优化 24 条建议（2020）】写的很不错，可以授权公众号 全栈修炼 转载吗？会注明作者及来源的，谢谢。

### ISSUE THREAD

**Issue by biaochenxuying** [woai3c/Front-end-articles#10]

**Comment by woai3c** [comment]
没问题，可以转载。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "woai3c/Front-end-articles"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 上午10:07
收件人:&nbsp;"woai3c/Front-end-articles"<Front-end-articles@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[woai3c/Front-end-articles] hello  大佬，文章【前端性能优化 24 条建议（2020）】写的很不错，可以授权公众号 全栈修炼 转载吗？会注明作者及来源的，谢谢。 (#10)
