### ISSUE TITLE
套件问题

### ISSUE THREAD

**Issue by Moocliu** [woai3c/Front-end-articles#27]
作者你好 如果你左边是一个套件怎么处理 这个套件拖拽到中间显示是两个选项而且两个选项是有联动效果的

**Comment by woai3c** [comment]
请在具体的项目下提问题.

**Comment by woai3c** [comment]
左边的组件栏，每一项都应该是一个组件。你说的套件，应该是一个比较复杂的组件，可以给当前组件设一个 children 属性，数组项为它的子组件。这样父子组件之间的属性就可以实现联动了。

如果是指属性联动，例如动画、样式这些，目前属性面板都只针对最顶层的组件，无法对嵌套的子组件进行更改。如果要实现这种效果，可以做一个独立的面板。当用户点击一个组件时，在该组件弹出一些选项，例如属性面板、事件、动画等等。这样就可以做到对嵌套子组件进行属性修改了。
