### ISSUE TITLE
页面上不是经常容易出现顶部的swiper组件嘛

### ISSUE THREAD

**Issue by jonny77** [woai3c/Front-end-articles#29]
我看issue里面有人提到好几次swiper. 可否考虑把这个做成一个标配功能.类似于ps里面的图层给他加个眼睛可以点开/关闭 一个一个进行编辑
另外 每个swiper项可能包含好几个元素 比如总的背景.标题. 以及标题和背景的切换动画

**Comment by woai3c** [comment]
请到具体的项目下提 issue
