### ISSUE TITLE
项目 visual-drag-demo-main 下载下来运行报错？

### ISSUE THREAD

**Issue by zky86** [woai3c/Front-end-articles#48]
[eslint] prettier.resolveConfig is not a function
Occurred while linting D:\root\visual-drag-demo-main\src\main.js:1
Rule: "prettier/prettier"

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
ERROR in [eslint] prettier.resolveConfig is not a function
Occurred while linting D:\root\visual-drag-demo-main\src\main.js:1
Rule: "prettier/prettier"

webpack compiled with 1 error

是什么问题呢？

**Comment by sunchencc** [comment]
挂机  出去玩O(∩_∩)O

**Comment by woai3c** [comment]
用 node 16+ 以上版本 然后使用 npm i 下载试试
